spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: rootroot
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8081

logging:
  level:
    root: info
    am.itspace: debug
  file:
    name: /Users/karen/Data/lessons/java2023-24/eshop/logs/eshop-%d{yyyy-MM-dd-HH-mm-ss}.%i.log
  logback:
    rollingpolicy:
      max-file-size: 1MB

eshop:
  picture:
    upload:
      directory: /Users/karen/Data/lessons/java2023-24/eshop/uploadDirectory